# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=erbjudande-topic
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false