$schema: "https://json-schema.org/draft/2020-12/schema"
$title: ErbjudandeTopicConfigSchema
type: object

required:
  - erbjudandeTopics

additionalProperties: false

properties:
  erbjudandeTopics:
    type: object
    additionalProperties: { type: string }